name: Run Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'    # هر دو ساعت یکبار

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install requests feedparser beautifulsoup4

      - name: Run bot
        run: python3 bot.py
