name: MasoudGOLDXBot Auto News & Analysis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # اجرا هر ۱ ساعت

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install requests feedparser beautifulsoup4 deep-translator

      - name: Run Fundamental (bot.py)
        run: python3 bot.py

      - name: Run Technical (tech_analysis.py)
        run: python3 tech_analysis.py
