name: MasoudGOLDXBot Auto Run

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install requests feedparser beautifulsoup4

      - name: Run Fundamental (bot.py)
        run: python3 bot.py

      - name: Run Technical (tech_analysis.py)
        run: python3 tech_analysis.py
