name: MasoudGOLDXBot Auto News & Analysis

on:
  schedule:
    - cron: '*/30 * * * *'  # اجرا هر 30 دقیقه
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install requests feedparser beautifulsoup4

      - name: Run Fundamental (bot.py)
        run: python3 bot.py

      - name: Run Technical (tech_analysis.py)
        run: python3 tech_analysis.py
