name: Run Telegram Bot Every 15 Minutes

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run the bot
        run: |
          pip install requests
          python3 bot.py
