name: MasoudGOLDXBot Auto News & Analysis

on:
  schedule:
    - cron: '0 * * * *'  # هر ساعت
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install feedparser beautifulsoup4 requests

      - name: Run Fundamental (bot.py)
        run: python3 bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
