name: Run MasoudGOLDX Technical Analysis Every 2 Hours

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tech analysis
        run: |
          pip install requests beautifulsoup4
          python3 tech_analysis.py
